name: myproject_functions
description: My project functions
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  firebase_functions_interop: ^1.0.0-dev
  node_io: ^1.0.0-dev

dev_dependencies:
  build_runner: ^0.7.9
  build_node_compilers: ^0.1.0

